### ISSUE TITLE
How do you run this?

### ISSUE THREAD

**Issue by delatbabel** [gothinkster/productionready-django-api#42]
How do you run this? There are no instructions in the README. I got as far as completing the build steps (I had to do pyenv install 3.5.3 instead of 3.5.2 because of openssl dependency issues) but there is nothing actually running.

**Comment by alicanguclukol** [comment]
You can follow the additional steps on [PR#15](https://github.com/gothinkster/django-realworld-example-app/pull/15/files)
You may also need to update 'pip' and 'python' commands as 'pip3' and 'python3'

**Comment by delatbabel** [comment]
Thanks, I left a comment on the PR.
