### ISSUE TITLE
cloning repository

### ISSUE THREAD

**Issue by 1c3beam** [gothinkster/productionready-django-api#45]
![Screenshot_2020-12-27-11-32-06-85](https://user-images.githubusercontent.com/50048043/103163152-266bd600-4835-11eb-878b-41b2cce365eb.png)

cant clone .why?

**Comment by Kristiyan-Ivanov** [comment]
Hi,

Github isn't able to authenticate you. You can find more info in the link
below.

https://stackoverflow.com/questions/12940626/github-error-message-permission-denied-publickey

**Comment by 1c3beam** [comment]
thanks,got it!
