### ISSUE TITLE
in authentication.Models

### ISSUE THREAD

**Issue by mkhan935** [gothinkster/productionready-django-api#6]
the function token creates a new token every time because it returns self._generate_jwt_token()
so when i use postman and a post request to login, i get a new token every time I correctly login.

When i use postman to a get request, how would it find the correct user if the token keeps changing?
Thats why I think this may be an error, I may most likely be wrong, I've asked on slack no response, I've asked on stackoverflow no response, this is my only shot

**Comment by mkhan935** [comment]
i think it should be jws.sign({'username': user.username, 'exp':dt}, settings.SECRET_KEY, algorithm='HS256')
again, not sure waiting for your expertise as I am using your course to learn

**Comment by sandeesh** [comment]
@mkhan935 to be fair the whole implementation of JWT in this project is very basic. The expiry is set to 60 days and there's check to invalidate the token on logout. We understand that the current implementation generates a new token on every login and the frontends only clear the local storage on logout and doesn't actually invalidate the token. This is not the ideal way to use JWT. But the team didn't mandate strict rules for JWT in the api spec in the early stage, so we're continuing with this for now.

The ideal usage of JWT in this scenario would be to keep the token short lived for a single request and reissue a new token on each request. Finally invalidate the token on logout.

**Comment by mkhan935** [comment]
I understand that, but if you followed the tutorial, they tell u to create a user, I did, then they have you login with the user, i did, then they implement a back-end and tell you to retrieve  a user using token, but the token changes, how am i supposed to retrieve the user? i did a get request using postman on the url api/user with the token in the headers section key/value. I also did it as api/user/?token="tokenhere",
it was then i noticed token keeps changing how would it retrieve a user

**Comment by sandeesh** [comment]
You store the token that you receive on login and use only that for further requests. You can ignore the different token displayed when fetching the current user using your stored token.

**Comment by mkhan935** [comment]
no no, the problem bro is that the token i receive on login, i use to get the current user and it doesn't work, i get the error "auth not provided". my code is exactly like the code thinkster has at this point. this is because we are not saving the token on login.

**Comment by sandeesh** [comment]
Ah ok. Can you check again if you're using the correct headers.

Key : Authorization
value : Token token.value.here

If nothing works i'll wait for someone from the team who handles this repo help you.

**Comment by mkhan935** [comment]
So try it like this on postman
/api/user
get request
headers
key:Authorization
value: Token token.value."the token string" ?

**Comment by sandeesh** [comment]
For example your token value is "exampletoken12345", then do this.
GET /api/user
Header key : Authorization
Header value : Token exampletoken12345

**Comment by mkhan935** [comment]
ok so this is what one of my tokens look like  thatkey= "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZXhwIjo1N30.9DMuXnLrBMgYdh-F-CWDUD9W3y_dViww7KqVVKN69lw"

i did the GET /api/user
Header key : Authorization
Value: Token thatKey (without quotes, tried it with quotes too)

this is what i mean, since to know the token for a user, we first login, see the token value, then
we go to api/user and do the get method, the token value has changed

this is now the error i get

{
  "user": {
    "detail": "Invalid authentication. Could not decode token."
  }
}

**Comment by mkhan935** [comment]
ok Sandeesh thanks a lot for the help, I took the secret key from this repo and used it instead of the secret key in my settings, and it worked. Thanks bro!
